# Navigation
alias la='ls -lAF'
alias ..='cd ..'
alias ...='cd ../..'
alias l='less'
alias BA='vim ~/.bashrc.user'
alias VIM='vim ~/.vimrc'

# Git
alias gs='git status'
alias gf='git fetch'
alias gco='git checkout'
alias gsi='git switch'
alias gow='git show'
alias gown='git show --name-only'
alias gadd='git add'
alias gu='git add -u'
alias giff='git diff'
alias giffs='git diff --staged'
alias gommit='git commit'
alias gommita='git commit --amend'
alias glog='git log --pretty=format:"%Cgreen %h - %<(20)%cn %<(10)%cr --- %s %C(auto) %d" --graph'
alias ggrep='git grep -n'
alias gsoft='git reset --soft'
alias ghard='git reset --hard'
